// Minimal fake OpenAI-compatible LLM server for manual integration testing.
// Responds with a write tool call, then a final message.
import { createServer } from "node:http"

let call = 0
const responses = [
  {
    choices: [
      {
        message: {
          content: "I'll create the file now.",
          tool_calls: [
            {
              id: "c1",
              type: "function",
              function: {
                name: "write",
                arguments: JSON.stringify({
                  path: "GENERATED.md",
                  content: "# Generated by Spectra\n\nThis file was written by the agent loop.\n",
                }),
              },
            },
          ],
        },
        finish_reason: "tool_calls",
      },
    ],
    usage: { prompt_tokens: 12, completion_tokens: 6 },
  },
  {
    choices: [
      { message: { content: "Created GENERATED.md successfully." }, finish_reason: "stop" },
    ],
    usage: { prompt_tokens: 9, completion_tokens: 4 },
  },
]

const server = createServer((req, res) => {
  let body = ""
  req.on("data", (c) => (body += c))
  req.on("end", () => {
    const response = responses[Math.min(call, responses.length - 1)]
    call++
    res.writeHead(200, { "content-type": "application/json" })
    res.end(JSON.stringify(response))
  })
})

const port = Number(process.env.PORT || 8799)
server.listen(port, "127.0.0.1", () => {
  console.log(`fake-llm listening on http://127.0.0.1:${port}/v1`)
})
